### ISSUE TITLE
Implement schema plugin for NXoff_geometry

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#103]
Geometry descriptions, in particular `NXoff_geometry` groups, can be too large to include in the initial command message. My proposed solution to this is to implement a plugin for `NXoff_geometry`. Since the order of vertex and face data in the datasets of this group are not order dependent it should be straightforward to stream them, in multiple messages if necessary.

I would be happy for myself, or another developer at ISIS, to implement this because it would allow us to provide feedback on documentation and "ease of use" for implementing plugins. There is an existing issue for the documentation #94.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1157
