### ISSUE TITLE
Implement schema plugin for NXtransformations for scanning instruments?

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#104]
Scanning instrument components, for example moving detector panels or a sample goniometer during an experiment may require _measured_ values being recorded in `NXtransformations` groups.

We need to find out if this is a genuine requirement or whether `NXtransformations` should contain only control set point values for the scan. In which case using the existing plugin for `NXlog`s for the measured values may be sufficient.

**Comment by mkoennecke** [comment]
The values in NXtransformations  MUST be measured values. Otherwise your data reduction will go bonkers. One measured value per scan point. Or a NXlog.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1182
