### ISSUE TITLE
Consider using CLI11 in place of getopt

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#114]
The syntax of `CLI11` looks much nicer than `getopt`. It also has the advantage of being cross-platform; `getopt` is POSIX-only.
The library is header-only and bincrafters have released a conan package.

https://github.com/CLIUtils/CLI11
https://bintray.com/bincrafters/public-conan/cli11%3Abincrafters

**Comment by dominikwerder** [comment]
:+1:

**Comment by SkyToGround** [comment]
@matthew-d-jones I second that, I have been moving the EFU to use the CLI11 library with good results. The outcome is less code and a more robust implementation.
