### ISSUE TITLE
Consider using JSON for Modern C++ in place of rapidjson

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#122]
See https://github.com/nlohmann/json
Conan recipe: https://github.com/vthiery/conan-jsonformoderncpp

I think this would make a large difference to the maintainability of the codebase and is thus compatible with the aims for the final few months of BrightnESS.

**Comment by mkoennecke** [comment]
This is certainly worth considering. But I wonder if it is our first priority at this stage of the project.

**Comment by matthew-d-jones** [comment]
@mkoennecke I suspect the effort involved would not be very large, but investigating that by making the change in the forwarder first might be a good option. The work also does not have to be done at PSI of course, we will have an additional person at ISIS from the summer.
I think it is fair not to give it highest priority.
