### ISSUE TITLE
FileWriterTask::hdf_init should use exceptions rather than return codes.

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/kafka-to-nexus#140]
Alternatively, it could use enums but exceptions are probably clearer and more standard.

**Comment by rerpha** [comment]
is this a case of throwing a runtime exception with the same message as the log messages (before the current return statements)? 
and in which case, should we remove the log messages or keep them?

**Comment by mkoennecke** [comment]
What about the LLVM coding standard? I believe we subscribed to that one. And the coding standard discourages RTTI and exceptions. This means the return code or an enum is it.

**Comment by SkyToGround** [comment]
@mkoennecke  Well, seeing as I am the one who brought it up in our last meeting: The LLVM coding standard does not allow for the use of RTTI and as an extension of this, exceptions. As I mentioned in that meeting, this is one of the rules in in the LLVM coding standard that we can not follow. I should probably write about all this on the confluence wiki somewhere...
