### ISSUE TITLE
Build issues under MacOSX

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#154]
There are currently several build issues with this project when generating an Xcode project from the CMake file. I will have a pull request related to this (GitHub) issue (hopefully) later today.

**Comment by SkyToGround** [comment]
Turns out that the problems were not that easy to fix but that there was an easy workaround. I will leave this issue for now though I will probably attempt to fix it in the future.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1183
