### ISSUE TITLE
Use clang-tidy to improve the code quality

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#165]
I have been able to fix a number of bugs and prevent many others by running clang-tidy on code bases that I have been responsible for. Thus this should probably be done for the _kafka-to-nexus_ project as well. The easiest way of doing this is by passing the `-DCMAKE_CXX_CLANG_TIDY` argument to CMake, e.g.:

```bash
cmake -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=*" ..
```
The code of the targets being built will then be analysed by clang-tidy. If no-one else takes in this issue, I will attempt to do it myself before the end of the year.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1155
