### ISSUE TITLE
Improve FileWriter::Msg

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#169]
Some notes on `FileWriter::Msg`:

* There is some dead code, e.g. `Msg::shared()` and `Msg::cheap()`. Is there some reason to not remove it?
* Is there a good reason for using a union for storing the data pointers? Using a `void`-pointer and re-interpret cast seems safer and cleaner to me. Or better yet: use the appropriate `std::unique_ptr`.
* Is there an argument against having an assignment operator?
* Due to the importance of this class, we really need unit tests for it.
* The pointers and sizes should probably be private.

@dominikwerder, @michele-brambilla do you have any comments on (primarily) point one and two?

**Comment by dominikwerder** [comment]
I still use these for some testing currently but also refactoring that part.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1184
