### ISSUE TITLE
The date library should be treated as a library

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#176]
Related to issue #157.

Seeing as the date library is quite a bit of code that is continually being updated and that it has been submitted for inclusion into the C++ standard, we should probably include it via conan instead of as source code in the repository.

**Comment by matthew-d-jones** [comment]
conan package is nearly ready: https://github.com/ess-dmsc/conan-date
Just need to track down a problem on Windows which occurs on the Jenkins node and not my local Windows machine.

**Comment by matthew-d-jones** [comment]
`date/2.4@ess-dmsc/stable` should be working on everything except Windows. Currently the source files for `date` (https://github.com/HowardHinnant/date)  are included in the kafka-to-nexus source. They'll need to be removed, `date` added to the conan dependencies, and then the CMake sorted out.

**Comment by matthew-d-jones** [comment]
If you end up using the bincrafters recipe then it should also be added to the linux and mac pipelines here: https://github.com/ess-dmsc/conan-external-libs
(so that the binaries exist on the ESS conan server). Afonso can advise if you have any problem figuring that out.
