### ISSUE TITLE
Dropping C++11 for C++14

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#177]
I noticed that the file writer is no longer being built with GCC 4.x by Jenkins. It is thus possible to move to C++14 by only switching a compiler flag.

Does anyone (@michele-brambilla @dominikwerder @matthew-d-jones ) have any objection to doing this?

**Comment by matthew-d-jones** [comment]
I guess the oldest compiler we are now supporting is gcc 5.4.1, on Ubuntu 16.04. I think that is the earliest gcc version to fully support C++14, so we should be fine to switch.

**Comment by dominikwerder** [comment]
Do you have anything specific in mind regarding c++14 usage?

**Comment by SkyToGround** [comment]
Yes, the most obvious (though currently minor) thing is that `std::make_unique` is a part of C++14.
More importantly, my current favourite mocking framework ([Trompeloeil](https://github.com/rollbear/trompeloeil)) requires C++14. This is also the case for the [C++ Guidelines support library](https://github.com/Microsoft/GSL) which I have been considering using.

Other than that there are some nice things in C++14 that could be useful, such as:
 * Improved lambdas
 * Improved `constexpr`
 * A bunch of additions to the `std`-library.

**Comment by dominikwerder** [comment]
Ah yes, some nice additions there. And no, I have nothing against that, except that we're not moving to 17 directly :-)

**Comment by matthew-d-jones** [comment]
The next long term support release of Ubuntu is out next week, so maybe we can drop Ubuntu 16.04 support fairly soon. I would need to wait until Mantid supports the new version though.

**Comment by matthew-d-jones** [comment]
I have no objections to dropping Ubuntu 16.04 and 17.10 from Jenkins builds and adding 18.04 instead now. At ISIS we've moved from 16.04 to 18.04 as Mantid supports 18.04 now.

**Comment by SkyToGround** [comment]
@matthew-d-jones I have gone ahead and removed Ubuntu 16.04 and 17.10 from the list of build nodes and replaces them with Ubuntu 18.04 as a part of fixing #157. I might have another pull request for adding C++14 support within a week or two.
