### ISSUE TITLE
Excessive CPU usage when kafka broker not present

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#183]
I have seen this problem on my (Mac) development machine. On thread uses up approximately 100% CPU printing (in this case) the following error message:
```
StreamMaster.h:178 [3]:  Error in topic adc_topic : Topic Partition Error
```

I can not be bothered to investigate more closely right now but I am assuming that the problem can be reproduced on Linux as well. Please fix at your earliest convenience.

**Comment by michele-brambilla** [comment]
Thank you for point this out. The filewriter assumes that the topics are already present in the brokers, if not it gives an error. I'll fix the issue of printing the error message asap.
