### ISSUE TITLE
Checking for null pointers should not be done with an implicit cast

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#19]
There are many places, for example in `CommandHandler.cxx` where checking for null pointers is done with an implicit cast to bool (`if (x)`). Instead explicitly check `if (x != nullptr)`.

**Comment by dominikwerder** [comment]
Out of curiosity, where do you see the issue?
Do you feel that the other form is easier to look at?

**Comment by matthew-d-jones** [comment]
I think it is better to be explicit. With `if (x != nullptr)` I can see what the code is doing at a glance. To understand that `if (x)` is actually doing the same I have to go and check what type `x` is.

**Comment by matthew-d-jones** [comment]
`gsl::not_null` is also nice, but you are mostly checking member variables where it wouldn't be suitable.

**Comment by matthew-d-jones** [comment]
@dominikwerder I won't complain if you close this issue if you don't want to make this change. It's subjective and we are all used to using `if (x)` for this; I would certainly have done it that way before we had `nullptr`.
