### ISSUE TITLE
SWMR cannot be disabled

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#217]
The default value of the "use SWMR" flag is what is used, even if `"use_hdf_swmr": false` is used in the "new" command.

The default value is set here:
https://github.com/ess-dmsc/kafka-to-nexus/blob/37a879f5d67eebbb1fe3a718db64fe67e8294ad5/src/FileWriterTask.h#L44

The filewriter does hit this line:
https://github.com/ess-dmsc/kafka-to-nexus/blob/37a879f5d67eebbb1fe3a718db64fe67e8294ad5/src/CommandHandler.cpp#L225

So I would guess that reopening the HDF file (a couple of lines further down) is not resetting SWMR file writing.
Note, my test of whether SWMR was used or not is to try to open the file with HDF5 v1.8. Therefore another possibility is that reopening the file does not reset the block indexing method, so maybe SWMR does get disabled but the file still cannot be read by v1.8.

Mantid and also h5py (when installed via pip) are still on v1.8.

**Comment by matthew-d-jones** [comment]
@dominikwerder @michele-brambilla 

For now I'll make a PR to temporarily set the default to disable SWMR so that I'm not blocked on a high priority ticket (involving testing the file writer with full ESS-style NeXus files).

**Comment by dominikwerder** [comment]
Fixed in #227
