### ISSUE TITLE
Incorrect behaviour if a busy file writer is asked to create another file

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#221]
If a file writer is already writing a file and it receives a message to create a new file with a different file name then it appears to give up on writing the first file and creates a new file. We need to decide what the correct behaviour is in this circumstance.

The behaviour should also be checked in the case that a different job id is used.

**Comment by michele-brambilla** [comment]
I can't reproduce this behaviour. In principle the job_id must be different for each file you write, whether you use the same file writer or two different.
Below the statistics for a single file writer that is writing two different files, you can see that the message count increases in both files.

```
{"files":{"1234567890abcdef":{"filename":"some.h5","topics":{"AMOR.area.detector-0":{"error_message_too_small":0,"error_no_flatbuffer_reader":0,"error_no_source_instance":0,"messages_processed":153}}},"1234567890abcdef-1":{"filename":"some-1.h5","topics":{"AMOR.area.detector-1":{"error_message_too_small":0,"error_no_flatbuffer_reader":0,"error_no_source_instance":0,"messages_processed":119}}}},"service_id":"kafka-to-nexus--host:pc11997.psi.ch--pid:5244","type":"filewriter_status_master"}
{"files":{"1234567890abcdef":{"filename":"some.h5","topics":{"AMOR.area.detector-0":{"error_message_too_small":0,"error_no_flatbuffer_reader":0,"error_no_source_instance":0,"messages_processed":155}}},"1234567890abcdef-1":{"filename":"some-1.h5","topics":{"AMOR.area.detector-1":{"error_message_too_small":0,"error_no_flatbuffer_reader":0,"error_no_source_instance":0,"messages_processed":120}}}},"service_id":"kafka-to-nexus--host:pc11997.psi.ch--pid:5244","type":"filewriter_status_master"}
{"files":{"1234567890abcdef":{"filename":"some.h5","topics":{"AMOR.area.detector-0":{"error_message_too_small":0,"error_no_flatbuffer_reader":0,"error_no_source_instance":0,"messages_processed":156}}},"1234567890abcdef-1":{"filename":"some-1.h5","topics":{"AMOR.area.detector-1":{"error_message_too_small":0,"error_no_flatbuffer_reader":0,"error_no_source_instance":0,"messages_processed":122}}}},"service_id":"kafka-to-nexus--host:pc11997.psi.ch--pid:5244","type":"filewriter_status_master"}
```

I think that a command that wants to use a job_id which is already in use should be rejected, but apparently at the moment this is not the file writer behaviour.

**Comment by matthew-d-jones** [comment]
@michele-brambilla Exactly, the problem is when a second file, with a different filename, is requested using the same `job_id`. As you say, the second request should be rejected.
