### ISSUE TITLE
Documentation of "streams" in readme is incorrect

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#237]
Documentation of `streams` in README is out-of-date: https://github.com/ess-dmsc/kafka-to-nexus/#options-for-schema-plugins

It should be documented that the stream object can be put in the `nexus_structure` instead of under the `streams` key.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1174
