### ISSUE TITLE
File-writer picks the wrong file-writing module

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#251]
Reading the code, there are no checks that both the flatbuffer id and source name is correct. Thus it is possible to have a message that has one flatbuffer id that will be sent to a writer module that expects another flatbuffer schema.

A solution would be to not use the source name as a key for the map of file writing instances but instead to use the flatbuffer id and source name as a key.

I have not verified this with code so I might be wrong but seriously doubt it.

**Comment by dominikwerder** [comment]
We must expect Flatbuffers of arbitrary schema id being send to a stream. That's why flatbuffers are verified using the flatbuffer library. Buffers which are not of the expected type are not processed.

Could you please describe the actual issue that you're facing? Do you see unexpected errors?

**Comment by dominikwerder** [comment]
What you describe should not happen, the filewriter verifies the flatbuffers before usage.

Flatbuffers come from untrusted sources and we must expect corrupted or even malicious data. Filewriter does these checks using the verifier from the flatbuffer library.

It is not very clear from your messages whether you are actually confronted with a corrupted file or any other error condition, or whether you are really asking if such a situation could come up.

If you actually see an error or unexpected output, could you please capture a flatbuffer of those two kinds and send them to me?

Or is this just a hypothetical "bug"?

**Comment by dominikwerder** [comment]
Looking through this again, I think that the `source_name` is actually accessed before verification, which is a problem and needs a fix.

Still, I can not see how you ended up with a corrupted HDF file in the end, so having such two buffers would still be very helpful.

**Comment by SkyToGround** [comment]
Having reread the code a few times now, I am very certain that this is a problem (a bug). It is caused by the way in which the (already instantiated) writer-module is selected as it is only selected using the source name of the flatbuffer. If you still do not understand how this is a problem I will write a code example that illustrated this tomorrow or next week.

**Comment by SkyToGround** [comment]
@dominikwerder Your suggested change **DOES NOT** fix this issue. I have a branch which fixes a bunch of things that will hopefully be merged with master tomorrow evening. I need that merged to simplify unit testing and when that is done I can write a test that exposes the problem (bug) caused by the current design.
