### ISSUE TITLE
FileWriter should have an option to set UID and GID or GOD for final files.  

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/kafka-to-nexus#260]

**Comment by matthew-d-jones** [comment]
@mattclarke Could you add some more details please? What is this for? Should it be written in the file?

**Comment by mattclarke** [comment]
I have no idea.
I think it was someone else's idea and I just wrote the ticket.

Anyone else remember this?

**Comment by mkoennecke** [comment]
At SINQ we write data files with the UID/GID of an instrument user. The file writer, however, is running as a service, usually as root. This is where this requirement to set the UID/GID of the file written by file writer comes from. The requirement for GOD is a joke. Now, we solved this problem  by running the file writer as a service owned by the user of our desire.  I think this can be closed for now but we ought to keep track that this issue exists. And may be someone from ESS may need to think how they want this done. If running the file writer under the UID of the user who ought to write the file is a solution. A proper solution will make the file writer more complex, probably requires it to be a suid program etc.

**Comment by mattclarke** [comment]
Thanks @mkoennecke.
Let's leave it open but I'll mark it as low priority

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1146
