### ISSUE TITLE
Exception thrown with no error log and insufficient information

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#263]
Hitting the exception thrown here: https://github.com/ess-dmsc/kafka-to-nexus/blob/364197a9139f9f717b7b498b2755597182a75f13/src/HDFFile.cpp#L95 results in the File Writer terminating and no error log being produced. The exception needs to be caught and sufficient information to find the cause (for example path of the dataset it is trying to create) should be logged.

**Comment by rerpha** [comment]
Exception is caught but currently stops writing to the file because it is rethrown in CommandHandler.cpp line 72

This should be logged and the file should continue writing without the dataset included
