### ISSUE TITLE
Stop time broken

### ISSUE THREAD

**Issue by michele-brambilla** [ess-dmsc/kafka-to-nexus#266]
The stop_time feature of the `Streamer` is does not work anymore. As soon as `StopTimestamp` is non-zero and a timeout happens the stream is closed. There is no actual check that the `StopTimestamp` is reached.

**Comment by SkyToGround** [comment]
I would argue that it is not broken other than that I should have removed the StopTimestamp option. The problem with `StopTimestamp` was that it was used to compare the timestamp of data to the system time of the local machine. This could in some cases result in weird, thus why I switched out the use of StopTimestamp for a timeout.

**Comment by SkyToGround** [comment]
I did not have time to work on this yesterday because of meetings much of the day. I will attempt to implement a unit tested fix today.

**Comment by SkyToGround** [comment]
Fix is now done, see PR #272.
