### ISSUE TITLE
Do we still need to support system-installed libraries?

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#271]
If not, cmake code can be greatly reduced, `Find` modules are not needed and we can just link against `CONAN_PKG::libraryname`

**Comment by matthew-d-jones** [comment]
Any objections to this @dominikwerder ?

**Comment by dominikwerder** [comment]
No. We use conan here on all systems.

**Comment by mkoennecke** [comment]
Well,

I disagree. I think if the stuff is there and working I am in favor of holding on to it. Do we really 
wankt to force conan onto everyone?

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1145
