### ISSUE TITLE
SEGV in test StreamerProcessTest on build server

### ISSUE THREAD

**Issue by dominikwerder** [ess-dmsc/kafka-to-nexus#299]
Some non-deterministic UB in `StreamerProcessTest` showed up on the build server during [unit tests](https://jenkins.esss.dk/dm/blue/organizations/jenkins/ess-dmsc%2Fkafka-to-nexus/detail/PR-297/4/pipeline).

The last output is:

```
...
[----------] 8 tests from StreamerProcessTest
[ RUN      ] StreamerProcessTest.CreationNotYetDone
/bin/bash: line 3:   849 Segmentation fault      (core dumped) ./tests/UnitTests
```

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1186
