### ISSUE TITLE
Profile FlatbufferMessage

### ISSUE THREAD

**Issue by mchorazak** [ess-dmsc/kafka-to-nexus#309]
Determine if the exceptions are a performance problem.

https://github.com/ess-dmsc/kafka-to-nexus/blob/9cf7b41ebeacec0b2ac1dbb55aecce9b4c307797/src/FlatbufferMessage.h#L31

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1144
