### ISSUE TITLE
Remove NeXusDataset helper classes when ready

### ISSUE THREAD

**Issue by mchorazak** [ess-dmsc/kafka-to-nexus#331]
Remove helper classes from NexusDataset.h/cpp when their functionality is added to h5cpp library.

https://github.com/ess-dmsc/kafka-to-nexus/blob/fa740305a1aeee312995dfed8e6680a399f4280f/src/NeXusDataset.h#L12

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1143
