### ISSUE TITLE
UB in Streamer test

### ISSUE THREAD

**Issue by dominikwerder** [ess-dmsc/kafka-to-nexus#358]
The test introduced [here](https://github.com/ess-dmsc/kafka-to-nexus/blame/12baeb406fe96d44ecb00967c3bc5d45dbb9223f/src/tests/StreamerTest.cpp#L52-L63) causes SEGV. 

It can obviously not work in the current form because it will lead to dereference of nullptr.

This bug only surfaces now, probably due to unrelated changes in other places as usual with undefined behavior.

I'm not very familiar with `Streamer` class, so I'm not sure what exactly we want to test here.

**Comment by SkyToGround** [comment]
Right, I will take a look at it. Note that the solution is **not** to remove the test. We want more tests, not fewer.

**Comment by dominikwerder** [comment]
https://github.com/ess-dmsc/kafka-to-nexus/pull/356#issuecomment-440971221
