### ISSUE TITLE
Re-write FindGoogletest.cmake module

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#39]
The FindGoogletest.cmake module specifically gives me a lot of headache. Does anyone oppose me re-writing it to better follow CMake find-module standards? If anyone does, can you tell me on what grounds?

**Comment by matthew-d-jones** [comment]
@SkyToGround  I'm just back from holiday and haven't caught up with the Conan situation yet, but if we are going to use that at some point then presumably it would solve your headache?

**Comment by SkyToGround** [comment]
It definitely would and I would prefer that as a solution. However, we have not yet decided to standardize on Conan so as an interim solution I suggest fixing the CMake file.

**Comment by matthew-d-jones** [comment]
@SkyToGround Fair enough

**Comment by michele-brambilla** [comment]
I'm playing around a little with Conan and have an experimental branch (not yet pushed) using it. I'll try to fix and test a couple of things today and then push if there's nothing against it

**Comment by matthew-d-jones** [comment]
Conan is working nicely so I'll close this ticket.
@SkyToGround Please reopen with details if there is any problem remaining.
