### ISSUE TITLE
How about attributes of NX_attributes?

### ISSUE THREAD

**Issue by nikhilbiyani** [ess-dmsc/kafka-to-nexus#45]
The current nexus_structure allows to include simple fields such as strings, floats and ints using the tag `NX_attributes`. For example:

```
            "instrument-02": {
		"NX_class": "NXinstrument",
		"NX_attributes": {
		    "notes": "some notes in form of an attribute",
		    "attribute_integer": 42,
		    "attribute_double": 42.0
		}
	    }
```

But it is quite possible that the some of the fields in `NX_attributes` have some attributes. For example: the position of a motor would have a `NX_attribute` called `value` which would in turn have an attribute called `unit`. How do we include that in the JSON?

**Comment by matthew-d-jones** [comment]
@nikhilbiyani Attributes cannot have attributes, I think the confusion here is the difference between children and attributes. In your example the `NXinstrument` class would have a child dataset called `value` which could have an attribute called `units`.
Does that make sense, or have I misunderstood your question?

**Comment by nikhilbiyani** [comment]
Yes, That's true. I confused attributes and datasets. The nexus structure before was not able to handle this case, but the current one is able to do this! Only thing that remains is if one wants to explicitly define the type of an attribute. @dominikwerder should we close this issue and make another one?

**Comment by matthew-d-jones** [comment]
It makes sense to create a new issue for that, otherwise the title is misleading.
