### ISSUE TITLE
Stopping the file writer not working properly

### ISSUE THREAD

**Issue by nikhilbiyani** [ess-dmsc/kafka-to-nexus#55]
When issuing the stop command with or without the `stop_time` does not flush the file until the file writer is closed. From the logs it is evident that the file writer sees a stop has been requested. But it does not flush the file and the data is still being written.

**Comment by matthew-d-jones** [comment]
If a stop timestamp is received but no further messages are received on one or more topics then the writer will not stop.
A possible solution: when the stop time + max latency time is reached by the system clock, it could query `offsetsForTimes` and unsubscribe from any partitions where the the stop offset has already been reached.

**Comment by mkoennecke** [comment]
In the ESS context stop is ill defined and this might be a topic for the upcoming ECP workshop. There was one requirement where data is streamed into a file, the sample moved to another place and more data regarding the sample being streamed even while the neutron DAQ has actually finished. This can be up to 15 min late! The file writer  in its current form implements this requirement. How we define when a file can finally be closed is not very well defined yet, at least for me.
