### ISSUE TITLE
NXtransformation should be NXtransformations

### ISSUE THREAD

**Issue by PeterC-DLS** [ess-dmsc/kafka-to-nexus#623]
I noticed a few typos: https://github.com/ess-dmsc/kafka-to-nexus/search?q=NXtransformation&type=code

See https://manual.nexusformat.org/classes/base_classes/NXtransformations.html

**Comment by SkyToGround** [comment]
Minor thing as the typos are almost entirely located in testing code. With that said, the fix is easy as well so I have made the appropriate changes in an unrelated PR that will be merged with master within an hour or two.

**Comment by PeterC-DLS** [comment]
Thanks, the one I noticed was in the command documentation (linked from Nexus Constructor).
