### ISSUE TITLE
Allow overwriting of HDF files if `overwrite: true`

### ISSUE THREAD

**Issue by dominikwerder** [ess-dmsc/kafka-to-nexus#64]
It should be optionally possible to overwrite an existing HDF file, for example in the case that the user wants to re-write a file.
In that case, the json command must include `overwrite: true` as safety guard.

**Comment by mkoennecke** [comment]
Overwriting an existing data file is heavily discouraged. Once written, a data file is almost holy. Only if you have a very good case to fix something you change it. Who is asking for this?

**Comment by dominikwerder** [comment]
We discussed that a NICOS user might want to ask for it. Currently, files can not be overwritten. I'll close the issue then.
