### ISSUE TITLE
Brokers unavailable terminates writer with runtime exception

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafka-to-nexus#66]
If the brokers go down and then come back up, when the next message is received by the writer it prints many broker availability errors and terminates with a runtime exception.

Possible cause is that errors are not currently handled on every poll, just when a message is successfully received.
No broker availability should not terminate the writer, it should just log an error and recover when the brokers are back.

**Comment by michele-brambilla** [comment]
Can you give me more details on the configuration you are using? I can't reproduce the failure. The only error I see after broker reconnection is 
``COMMITFAIL|rdkafka#consumer-3| [thrd:main]: Offset commit (cgrp auto commit timer) failed for 1/1 partition(s): Local: Waiting for coordinator``
and the write continues as expected

**Comment by matthew-d-jones** [comment]
Thanks for looking at this, I'm also unable to reproduce the problem on current master so I'll close this issue.
I was having problems with strings before #65 went in, so the crash may have been related to that.
