### ISSUE TITLE
Document configuration

### ISSUE THREAD

**Issue by mkoennecke** [ess-dmsc/kafka-to-nexus#88]
There is no documentation on  how kafka-to-nexus is configured. Some data is taken from a configuration file, some from the json for writing files etc. These things are required:
- a description of how the configuration system works
- where each configuration class takes its data from
- a reference for the configuration file syntax and the meaning of each parameter when not obvious

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1159
