### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by mkoennecke** [ess-dmsc/kafka-to-nexus#93]
Improve the documentation in README.md. There are various points:
- The REAME should be shorter, overview style, and link into other documents for further reference.
- The links into confluence point to outdated information which either must be updated or removed. Otherwise this is just plain confusing.
- The build process should be documented with and without conan. For conan a warning is in order that conan dumps a lot of stuff in $(HOME)/.conan. 
- All information in README.md should be checked if it is still accurate.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1158
